spring.application.name=gateway
server.port=8080

# MySQL ? mysql-gateway container (porta 3310)
spring.datasource.url=jdbc:mysql://localhost:3310/db_gateway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=novapay
spring.datasource.password=novapay_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Rotas do gateway ? cada prefixo � redirecionado para o servi�o correspondente
spring.cloud.gateway.server.webmvc.routes[0].id=account-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/accounts/**

spring.cloud.gateway.server.webmvc.routes[1].id=transaction-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/transactions/**

spring.cloud.gateway.server.webmvc.routes[2].id=fraud-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/fraud/**

spring.cloud.gateway.server.webmvc.routes[3].id=notification-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/notifications/**

# JWT ? m�nimo 32 caracteres para HMAC-SHA256
jwt.secret=novapay-secret-key-2026-must-be-256-bits-minimum-for-hmac-sha
jwt.expiration=86400000
